version: '3'
services:
  order:
    image: filipklimes-diploma/example-order-service
    ports:
      - "5501:5501"
      - "5551:5551"
    depends_on:
      - "product"
      - "billing"
      - "shipping"
      - "user"
    links:
      - product
      - user
      - billing
      - shipping

  product:
    image: filipklimes-diploma/example-product-service
    ports:
      - "5502:5502"
      - "5552:5552"
    depends_on:
      - "user"
    links:
      - user:user

  user:
    image: filipklimes-diploma/example-user-service
    ports:
      - "5503:5503"
      - "5553:5553"

  shipping:
    image: filipklimes-diploma/example-shipping-service
    ports:
      - "5504:5504"
      - "5554:5554"

  billing:
    image: filipklimes-diploma/example-billing-service
    ports:
      - "5505:5505"
      - "5555:5555"

  ui:
    image: filipklimes-diploma/example-ui-service
    ports:
      - "8080:8080"
    depends_on:
      - "product"
      - "billing"
      - "shipping"
      - "user"
      - "order"
    links:
      - product
      - order
      - user

  central-administration:
    image: filipklimes-diploma/central-administration
    ports:
      - "5600:5600"
    depends_on:
      - "product"
      - "billing"
      - "shipping"
      - "user"
      - "order"
      - "ui"
    links:
      - product
      - order
      - user
      - billing
      - shipping
