# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business_context.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='business_context.proto',
  package='businessContext',
  syntax='proto2',
  serialized_pb=_b('\n\x16\x62usiness_context.proto\x12\x0f\x62usinessContext\"0\n\x12\x45xpressionProperty\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"\x83\x01\n\nExpression\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x37\n\nproperties\x18\x02 \x03(\x0b\x32#.businessContext.ExpressionProperty\x12.\n\targuments\x18\x03 \x03(\x0b\x32\x1b.businessContext.Expression\"S\n\x13PreconditionMessage\x12\x0c\n\x04name\x18\x01 \x02(\t\x12.\n\tcondition\x18\x02 \x02(\x0b\x32\x1b.businessContext.Expression\"\x9d\x01\n\x14PostConditionMessage\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x30\n\x04type\x18\x02 \x02(\x0e\x32\".businessContext.PostConditionType\x12\x15\n\rreferenceName\x18\x03 \x02(\t\x12.\n\tcondition\x18\x04 \x02(\x0b\x32\x1b.businessContext.Expression\"\xcc\x01\n\x16\x42usinessContextMessage\x12\x0e\n\x06prefix\x18\x01 \x02(\t\x12\x0c\n\x04name\x18\x02 \x02(\t\x12\x18\n\x10includedContexts\x18\x03 \x03(\t\x12;\n\rpreconditions\x18\x04 \x03(\x0b\x32$.businessContext.PreconditionMessage\x12=\n\x0epostConditions\x18\x05 \x03(\x0b\x32%.businessContext.PostConditionMessage\"\\\n\x1f\x42usinessContextsResponseMessage\x12\x39\n\x08\x63ontexts\x18\x01 \x03(\x0b\x32\'.businessContext.BusinessContextMessage\"\x8a\x01\n\x1d\x42usinessContextRequestMessage\x12\x18\n\x10requiredContexts\x18\x01 \x03(\t\x12\x19\n\x11requestedFromName\x18\x02 \x02(\t\x12\x19\n\x11requestedFromHost\x18\x03 \x02(\t\x12\x19\n\x11requestedFromPort\x18\x04 \x02(\x05*w\n\x11PostConditionType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x17\n\x13\x46ILTER_OBJECT_FIELD\x10\x01\x12\x1a\n\x16\x46ILTER_LIST_OF_OBJECTS\x10\x02\x12 \n\x1c\x46ILTER_LIST_OF_OBJECTS_FIELD\x10\x03\x32\x8c\x01\n\x15\x42usinessContextServer\x12s\n\rFetchContexts\x12..businessContext.BusinessContextRequestMessage\x1a\x30.businessContext.BusinessContextsResponseMessage\"\x00')
)

_POSTCONDITIONTYPE = _descriptor.EnumDescriptor(
  name='PostConditionType',
  full_name='businessContext.PostConditionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILTER_OBJECT_FIELD', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILTER_LIST_OF_OBJECTS', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FILTER_LIST_OF_OBJECTS_FIELD', index=3, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=914,
  serialized_end=1033,
)
_sym_db.RegisterEnumDescriptor(_POSTCONDITIONTYPE)

PostConditionType = enum_type_wrapper.EnumTypeWrapper(_POSTCONDITIONTYPE)
UNKNOWN = 0
FILTER_OBJECT_FIELD = 1
FILTER_LIST_OF_OBJECTS = 2
FILTER_LIST_OF_OBJECTS_FIELD = 3



_EXPRESSIONPROPERTY = _descriptor.Descriptor(
  name='ExpressionProperty',
  full_name='businessContext.ExpressionProperty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='businessContext.ExpressionProperty.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='businessContext.ExpressionProperty.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=91,
)


_EXPRESSION = _descriptor.Descriptor(
  name='Expression',
  full_name='businessContext.Expression',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='businessContext.Expression.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='properties', full_name='businessContext.Expression.properties', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='businessContext.Expression.arguments', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=225,
)


_PRECONDITIONMESSAGE = _descriptor.Descriptor(
  name='PreconditionMessage',
  full_name='businessContext.PreconditionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='businessContext.PreconditionMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='condition', full_name='businessContext.PreconditionMessage.condition', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=310,
)


_POSTCONDITIONMESSAGE = _descriptor.Descriptor(
  name='PostConditionMessage',
  full_name='businessContext.PostConditionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='businessContext.PostConditionMessage.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='businessContext.PostConditionMessage.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='referenceName', full_name='businessContext.PostConditionMessage.referenceName', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='condition', full_name='businessContext.PostConditionMessage.condition', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=313,
  serialized_end=470,
)


_BUSINESSCONTEXTMESSAGE = _descriptor.Descriptor(
  name='BusinessContextMessage',
  full_name='businessContext.BusinessContextMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prefix', full_name='businessContext.BusinessContextMessage.prefix', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='businessContext.BusinessContextMessage.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='includedContexts', full_name='businessContext.BusinessContextMessage.includedContexts', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preconditions', full_name='businessContext.BusinessContextMessage.preconditions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='postConditions', full_name='businessContext.BusinessContextMessage.postConditions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=473,
  serialized_end=677,
)


_BUSINESSCONTEXTSRESPONSEMESSAGE = _descriptor.Descriptor(
  name='BusinessContextsResponseMessage',
  full_name='businessContext.BusinessContextsResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contexts', full_name='businessContext.BusinessContextsResponseMessage.contexts', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=679,
  serialized_end=771,
)


_BUSINESSCONTEXTREQUESTMESSAGE = _descriptor.Descriptor(
  name='BusinessContextRequestMessage',
  full_name='businessContext.BusinessContextRequestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requiredContexts', full_name='businessContext.BusinessContextRequestMessage.requiredContexts', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestedFromName', full_name='businessContext.BusinessContextRequestMessage.requestedFromName', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestedFromHost', full_name='businessContext.BusinessContextRequestMessage.requestedFromHost', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requestedFromPort', full_name='businessContext.BusinessContextRequestMessage.requestedFromPort', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=774,
  serialized_end=912,
)

_EXPRESSION.fields_by_name['properties'].message_type = _EXPRESSIONPROPERTY
_EXPRESSION.fields_by_name['arguments'].message_type = _EXPRESSION
_PRECONDITIONMESSAGE.fields_by_name['condition'].message_type = _EXPRESSION
_POSTCONDITIONMESSAGE.fields_by_name['type'].enum_type = _POSTCONDITIONTYPE
_POSTCONDITIONMESSAGE.fields_by_name['condition'].message_type = _EXPRESSION
_BUSINESSCONTEXTMESSAGE.fields_by_name['preconditions'].message_type = _PRECONDITIONMESSAGE
_BUSINESSCONTEXTMESSAGE.fields_by_name['postConditions'].message_type = _POSTCONDITIONMESSAGE
_BUSINESSCONTEXTSRESPONSEMESSAGE.fields_by_name['contexts'].message_type = _BUSINESSCONTEXTMESSAGE
DESCRIPTOR.message_types_by_name['ExpressionProperty'] = _EXPRESSIONPROPERTY
DESCRIPTOR.message_types_by_name['Expression'] = _EXPRESSION
DESCRIPTOR.message_types_by_name['PreconditionMessage'] = _PRECONDITIONMESSAGE
DESCRIPTOR.message_types_by_name['PostConditionMessage'] = _POSTCONDITIONMESSAGE
DESCRIPTOR.message_types_by_name['BusinessContextMessage'] = _BUSINESSCONTEXTMESSAGE
DESCRIPTOR.message_types_by_name['BusinessContextsResponseMessage'] = _BUSINESSCONTEXTSRESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['BusinessContextRequestMessage'] = _BUSINESSCONTEXTREQUESTMESSAGE
DESCRIPTOR.enum_types_by_name['PostConditionType'] = _POSTCONDITIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExpressionProperty = _reflection.GeneratedProtocolMessageType('ExpressionProperty', (_message.Message,), dict(
  DESCRIPTOR = _EXPRESSIONPROPERTY,
  __module__ = 'business_context_pb2'
  # @@protoc_insertion_point(class_scope:businessContext.ExpressionProperty)
  ))
_sym_db.RegisterMessage(ExpressionProperty)

Expression = _reflection.GeneratedProtocolMessageType('Expression', (_message.Message,), dict(
  DESCRIPTOR = _EXPRESSION,
  __module__ = 'business_context_pb2'
  # @@protoc_insertion_point(class_scope:businessContext.Expression)
  ))
_sym_db.RegisterMessage(Expression)

PreconditionMessage = _reflection.GeneratedProtocolMessageType('PreconditionMessage', (_message.Message,), dict(
  DESCRIPTOR = _PRECONDITIONMESSAGE,
  __module__ = 'business_context_pb2'
  # @@protoc_insertion_point(class_scope:businessContext.PreconditionMessage)
  ))
_sym_db.RegisterMessage(PreconditionMessage)

PostConditionMessage = _reflection.GeneratedProtocolMessageType('PostConditionMessage', (_message.Message,), dict(
  DESCRIPTOR = _POSTCONDITIONMESSAGE,
  __module__ = 'business_context_pb2'
  # @@protoc_insertion_point(class_scope:businessContext.PostConditionMessage)
  ))
_sym_db.RegisterMessage(PostConditionMessage)

BusinessContextMessage = _reflection.GeneratedProtocolMessageType('BusinessContextMessage', (_message.Message,), dict(
  DESCRIPTOR = _BUSINESSCONTEXTMESSAGE,
  __module__ = 'business_context_pb2'
  # @@protoc_insertion_point(class_scope:businessContext.BusinessContextMessage)
  ))
_sym_db.RegisterMessage(BusinessContextMessage)

BusinessContextsResponseMessage = _reflection.GeneratedProtocolMessageType('BusinessContextsResponseMessage', (_message.Message,), dict(
  DESCRIPTOR = _BUSINESSCONTEXTSRESPONSEMESSAGE,
  __module__ = 'business_context_pb2'
  # @@protoc_insertion_point(class_scope:businessContext.BusinessContextsResponseMessage)
  ))
_sym_db.RegisterMessage(BusinessContextsResponseMessage)

BusinessContextRequestMessage = _reflection.GeneratedProtocolMessageType('BusinessContextRequestMessage', (_message.Message,), dict(
  DESCRIPTOR = _BUSINESSCONTEXTREQUESTMESSAGE,
  __module__ = 'business_context_pb2'
  # @@protoc_insertion_point(class_scope:businessContext.BusinessContextRequestMessage)
  ))
_sym_db.RegisterMessage(BusinessContextRequestMessage)



_BUSINESSCONTEXTSERVER = _descriptor.ServiceDescriptor(
  name='BusinessContextServer',
  full_name='businessContext.BusinessContextServer',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=1036,
  serialized_end=1176,
  methods=[
  _descriptor.MethodDescriptor(
    name='FetchContexts',
    full_name='businessContext.BusinessContextServer.FetchContexts',
    index=0,
    containing_service=None,
    input_type=_BUSINESSCONTEXTREQUESTMESSAGE,
    output_type=_BUSINESSCONTEXTSRESPONSEMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUSINESSCONTEXTSERVER)

DESCRIPTOR.services_by_name['BusinessContextServer'] = _BUSINESSCONTEXTSERVER

# @@protoc_insertion_point(module_scope)
